### ISSUE TITLE
FIx trafficlight removal from background also

### ISSUE THREAD

**Issue by tfhuhtal** [UniversityOfHelsinkiCS/lomake#1135]
When there are many traffic lights, when I try to delete one of them, it is correctly removed in the modal but in the actual page (the one dimmed in the background) the number of traffic lights is actually increasing. When I close the modal, the extra lights are still there. Page refresh fixes the situation, so this is just a React state issue

![image](https://github.com/user-attachments/assets/de325f2e-b605-4972-95ee-c84e08aa10b3)

**Comment by Mukku27** [comment]
i would like to work on it please assign it to me
