### ISSUE TITLE
offer a way to explore questions on question basis

### ISSUE THREAD

**Issue by Sendouc** [UniversityOfHelsinkiCS/lomake#272]
Right now we offer ways to view questions "horizontally" (so per answer). We could also offer ways to explore data by a question. This would be especially useful for users with a ton of answers to go through. Here is an example:

1. Choose question by clicking the matching header on overview
2. This opens a scrollable list with all the answers to this question
3. Allow filtering by word e.g. "howulearn" and this filters to only show answers by this keyword - bolding it.
  - This could also be triggered by clicking a word on the world cloud

**Comment by saarasat** [comment]
Done with the "new" Report views.
