### ISSUE TITLE
Create downloadable csv export for system wide answers

### ISSUE THREAD

**Issue by markokoskinen2037** [UniversityOfHelsinkiCS/lomake#323]
Format should be something like this:
| Programme name|      Answer 1     |  Answer 2|
|----------|:-------------:|------:|
| prog 1 |  answer 1 |  answer 2  |
| prog 2 |  answer 1 |  answer 2  |
| prog 3 | answer 1  |  answer 2  |

**Comment by Sendouc** [comment]
Can maybe reuse this [this component](https://github.com/UniversityOfHelsinkiCS/lomake/blob/master/client/components/FormView/CSVDownload.js)

Just need to note that currently it is pretty specific. So might have to refactor it first. Of course creating a new component is valid too if it seems easier.
