### ISSUE TITLE
Create csv export for 'traffic light' summary

### ISSUE THREAD

**Issue by markokoskinen2037** [UniversityOfHelsinkiCS/lomake#324]
From which OSPA can generate their own visualizations

**Comment by Sendouc** [comment]
Can maybe reuse this [this component](https://github.com/UniversityOfHelsinkiCS/lomake/blob/master/client/components/FormView/CSVDownload.js)

Just need to note that currently it is pretty specific. So might have to refactor it first. Of course creating a new component is valid too if it seems easier.
