### ISSUE TITLE
Make smily-faces in overview page appear more "clickable"

### ISSUE THREAD

**Issue by markokoskinen2037** [UniversityOfHelsinkiCS/lomake#325]
At least 2 users have had no idea that they can be clicked.
![image](https://user-images.githubusercontent.com/22393121/92109688-24978600-edf2-11ea-819e-3c0dab4ea9ed.png)

**Comment by Sendouc** [comment]
Additionally clicking the cell should have the same effect as clicking the smiley. Maybe show slightly different bg color when hovering or something?
