### ISSUE TITLE
CSV export is not working as intended

### ISSUE THREAD

**Issue by markokoskinen2037** [UniversityOfHelsinkiCS/lomake#330]
linebreaks in answers causes issues, parsing the csv in excel/libreoffice "fails"

**Comment by saarasat** [comment]
There was no ready-made handling of all the special characters in the react-csv -library so some additional replacements has been made keeping in mind the editor used for the textarea.

This has now been tested with LibreOffice and Excel Desktop App, and should work with both (**Excel online is missing the data-to-columns -option, so CSVs are not optimal there in any case**):

And the following cases are now taken into consideration:

1. Editor-created bullet
2. Editor-created indendated (i.e. smaller bullet)
3. Self-made bullet (" - ")
4. Hyphen in the middle of a word
5. Semicolon
6. Double and single quotes
7. Carriage return
8. Bolded text
9. New lines

If there are other marks that are missing, they should be easy to escape at [the CSVDownload-component](https://github.com/UniversityOfHelsinkiCS/lomake/blob/master/client/components/FormView/CSVDownload.js)

I'll make a release of this fix today or tomorrow.
