### ISSUE TITLE
Fix flaky Cypress tests

### ISSUE THREAD

**Issue by Sendouc** [UniversityOfHelsinkiCS/lomake#381]
Apparently especially tests that include writing sometimes pass and sometimes fail. In addition seems that this behaviour is more prevalent when using via GitHub actions.

**Comment by saarasat** [comment]
Possibly hopefully fixed in: https://github.com/UniversityOfHelsinkiCS/lomake/commit/b1cd345d54eabfc2d465cc50fe9980267b96648f
