### ISSUE TITLE
Traffic lights on-hover text translations

### ISSUE THREAD

**Issue by sinikala** [UniversityOfHelsinkiCS/lomake#684]

**Comment by Thiagoramos456** [comment]
Hey! I'm impressed by your project and i would like to contribute to this issue. Could you please provide more detail about what needs to be done?

**Comment by sinikala** [comment]
Hi @Thiagoramos456! 
This ticket was maybe a bit vaguely named. The issue was actually just a one minute task copying already existing translations from one place to another and is now completed.

Thank you for your interest in our project howver! Have a good day! :sunflower:
