### ISSUE TITLE
Default language fakd in koulutusuudistus

### ISSUE THREAD

**Issue by Veikkosuhonen** [UniversityOfHelsinkiCS/lomake#714]
Should be fi for most ppl who tested but was en

**Comment by iPegii** [comment]
Defaults to browser language

[Code](https://github.com/UniversityOfHelsinkiCS/lomake/blob/master/client/util/i18n.js)

![lomake-i18n](https://github.com/UniversityOfHelsinkiCS/lomake/assets/51372604/7401d037-5e9d-4240-8aff-18e9506459d7)
