### ISSUE TITLE
koulutusuudistus - ohjelmat, sections missing )fixed with kludge, check if ok)

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/lomake#725]
EDIT: this is now fixed with this kludge https://github.com/UniversityOfHelsinkiCS/lomake/commit/3221c819629f3553a5ed5143f42c918edf22f0a6#diff-27d4684325cf0d8a66adc218c14eb9ff29b5de98610c52e1388c050e10f9fd9b

no idea if it is a proper fix, please check

eg https://opetushallinto.cs.helsinki.fi/tilannekuva/degree-reform/form/T921107 has not these despite those are seen left

<img width="1006" alt="image" src="https://github.com/UniversityOfHelsinkiCS/lomake/assets/523235/c198de0a-d67e-4832-b964-7eca051cf3e2">

**Comment by iPegii** [comment]
Fixed in https://github.com/UniversityOfHelsinkiCS/lomake/releases/tag/v3.5.25
