### ISSUE TITLE
in most of the lomake overview the "admin symbol" is on wrong line

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/lomake#843]
now it is:

<img width="1588" alt="image" src="https://github.com/UniversityOfHelsinkiCS/lomake/assets/523235/fa2c48de-ea01-406f-b864-a6ad287cfc0a">

should be:

<img width="1023" alt="image" src="https://github.com/UniversityOfHelsinkiCS/lomake/assets/523235/d9c4e481-8ec0-40ba-beb0-67eb707a6c74">

tdk katselmus does it right

**Comment by iPegii** [comment]
fixed now
