### ISSUE TITLE
H74 name fakd in "Tilannekuvalomakkeen vastaukset"

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/lomake#901]
https://opetushallinto.cs.helsinki.fi/tilannekuva/report?form=5

<img width="541" alt="image" src="https://github.com/UniversityOfHelsinkiCS/lomake/assets/523235/0d7e7bd8-6adb-44d5-aa3b-36dd7a78af73">

should be

```  
{
    code: 'H74',
    name: {
      fi: 'Svenska social- och kommunalhögskolan',
      en: 'Swedish School of Social Science',
      se: 'Svenska social- och kommunalhögskolan',
    },
  },
```

**Comment by iPegii** [comment]
Fixed in https://github.com/UniversityOfHelsinkiCS/lomake/releases/tag/v3.14.1
